export {Cadastro} from './Cadastro'
export {DevicesDetails} from './DevicesDetails'
export {Devices} from './Devices'
export {Home} from './Home'
export {Login} from './Login'
export {Perfil} from './Perfil'